//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_sign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOpciones
    {
        public int Id { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<int> Opciones { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Termino { get; set; }
    
        public virtual Opciones Opciones1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
