//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_sign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opciones()
        {
            this.DetalleOpciones = new HashSet<DetalleOpciones>();
        }
    
        public int Id { get; set; }
        public string Icono { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Prioridad { get; set; }
        public string Cabecera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOpciones> DetalleOpciones { get; set; }
    }
}
